version: '4'

services:
        tesis:
            build:
              context: ./
              dockerfile: Dockerfile
              args:
                - PRODUCTBD=${POSTGRES_URL}
            image: tesis
            ports:
              - ${PORT}:${PORT}
            environment:
              - PORT=${PORT}
              - PUBLIC_PATH=${PUBLIC_PATH}
              - MAILER_SERVICE=${MAILER_SERVICE}
              - MAILER_EMAIL=${MAILER_EMAIL}
              - MAILER_KEY=${MAILER_KEY}
              - POSTGRES_URL=${POSTGRES_URL}
              - POSTGRES_USER=${POSTGRES_USER}
              - POSTGRES_DB=${POSTGRES_DB}
              - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
              - CLOUDINARY_URL=${CLOUDINARY_URL}
              - WEBSERVICE_URL=${WEBSERVICE_URL}
              - SECRET_JWT=${SECRET_JWT}
              - NODE_ENV=${NODE_ENV}